### ISSUE TITLE
ERROR: LoadError: ArgumentError: Module DiffEqBaseQ not found in current path

### ISSUE THREAD

**Issue by rohith14** [JuliaDiffEq/MATLABDiffEq.jl#3]
# I tried running this example and ran into an error

Pkg.add("ParameterizedFunctions")
#Pkg.add("DiffEqBaseQ")
using DiffEqBase, ParameterizedFunctions, MATLABDiffEq
f = @ode_def_bare RigidBodyBench begin
  dy1  = I1*y2*y3
  dy2  = I2*y1*y3
  dy3  = I3*y1*y2 + 0.25*sin(t)^2
end I1=-2 I2=1.25 I3=-.5
prob = ODEProblem(f,[1.0;0.0;0.9],(0.0,100.0))
alg = MATLABDiffEq.ode45()
algstr = string(typeof(alg).name.name)

# Error
NFO: Package ParameterizedFunctions is already installed
INFO: METADATA is out-of-date — you may not have the latest version of ParameterizedFunctions
INFO: Use `Pkg.update()` to get the latest versions of your packages

WARNING: deprecated syntax "abstract MATLABAlgorithm<:AbstractODEAlgorithm" at C:\Users\rbakkann\.julia\v0.6\MATLABDiffEq\src\MATLABDiffEq.jl:11.
Use "abstract type MATLABAlgorithm<:AbstractODEAlgorithm end" instead.
INFO: Precompiling module MATLABDiffEq.

WARNING: deprecated syntax "abstract MATLABAlgorithm<:AbstractODEAlgorithm" at C:\Users\rbakkann\.julia\v0.6\MATLABDiffEq\src\MATLABDiffEq.jl:11.
Use "abstract type MATLABAlgorithm<:AbstractODEAlgorithm end" instead.
ERROR: LoadError: ArgumentError: Module DiffEqBaseQ not found in current path.
Run `Pkg.add("DiffEqBaseQ")` to install the DiffEqBaseQ package.
Stacktrace:
 [1] _require(::Symbol) at .\loading.jl:428
 [2] require(::Symbol) at .\loading.jl:398
 [3] include_from_node1(::String) at .\loading.jl:569
 [4] include(::String) at .\sysimg.jl:14
 [5] anonymous at .\<missing>:2
while loading C:\Users\rbakkann\.julia\v0.6\MATLABDiffEq\src\MATLABDiffEq.jl, in expression starting on line 6
Failed to precompile MATLABDiffEq to C:\Users\rbakkann\.julia\lib\v0.6\MATLABDiffEq.ji.

Stacktrace:
 [1] compilecache(::String) at .\loading.jl:703
 [2] _require(::Symbol) at .\loading.jl:490
 [3] require(::Symbol) at .\loading.jl:398
 [4] include_string(::String, ::String) at .\loading.jl:515
# I installed the package : 
Pkg.clone("https://github.com/JuliaDiffEq/MATLABDiffEq.jl")

**Comment by rohith14** [comment]
I think the line 6 '@reexport using DiffEqBaseQ' should be '@reexport using DiffEqBase'.  Is that right ?

**Comment by ChrisRackauckas** [comment]
Yes. I made a change somewhere along the line and accidentally added that q....

**Comment by ChrisRackauckas** [comment]
Should be good now. Sorry, this package can't have CI because MATLAB won't work with Travis. Also, it's unregistered so I don't update it often since I don't find it useful. But it's fun and hopefully it works again. Thanks for the issue!
