### ISSUE TITLE
UndefVarError: ode_workprecision_set not defined

### ISSUE THREAD

**Issue by rohith14** [JuliaDiffEq/MATLABDiffEq.jl#4]
# I get the error,
UndefVarError: ode_workprecision_set not defined

Stacktrace:
 [1] include_string(::String, ::String) at .\loading.jl:515

# for the following code
using OrdinaryDiffEq, ODEInterfaceDiffEq, Plots, ODE
using DiffEqDevTools
abstols = 1./10.^(6:13)
reltols = 1./10.^(3:10)
sol = solve(prob,Vern7(),abstol=1/10^14,reltol=1/10^14)
test_sol = TestSolution(sol)
plotly()
setups = [Dict(:alg=>DP5())
          Dict(:alg=>dopri5())
          Dict(:alg=>BS5())
          Dict(:alg=>Tsit5())
          Dict(:alg=>Vern6())
          Dict(:alg=>Vern7())
          Dict(:alg=>MATLABDiffEq.ode45())
  ]
wp = ode_workprecision_set(prob,abstols,reltols,setups;appxsol=test_sol,dense=false,save_everystep=false,numruns=1000,maxiters=10000000,ttimeseries_errors=false,verbose=false)
plot(wp)

# Am i missing any module ?

Thanks

**Comment by ChrisRackauckas** [comment]
That should do it. This is why lack of CI is a problem haha.

**Comment by rohith14** [comment]
Thank you for the quick response
