### ISSUE TITLE
MATLABDiffEq Load Error 

### ISSUE THREAD

**Issue by NirvikNU** [JuliaDiffEq/MATLABDiffEq.jl#7]
Hi,
I was able to add MATLABDiffEq successfully including its dependencies, however while trying out the worked out example in this package i keep getting a ERROR: **LoadError: UndefVarError: AlgType not defined** Here is a screenshot:
![Screenshot from 2019-10-15 19-32-26](https://user-images.githubusercontent.com/56455477/66879166-a8e6dd80-ef82-11e9-864f-40b5f72f1de6.png)
Please help.
Thanks

**Comment by ChrisRackauckas** [comment]
Xref: https://discourse.julialang.org/t/matlabdiffeq-load-error/29992/6

**Comment by ChrisRackauckas** [comment]
This is being put on the back burner due to other obligations having
priority, but please feel free to ping me in December to remind me about
this.

**Comment by ChrisRackauckas** [comment]
This is working on 1.0 now: https://github.com/JuliaDiffEq/MATLABDiffEq.jl/commit/c3b9dc7e70ad90129b42c87bb619e88137d7249f

**Comment by NirvikNU** [comment]
There is a registry issue:
```
(v1.2) pkg> add MATLABDiffEq
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
ERROR: Package MATLABDiffEq [53bc815d-88dc-556a-83aa-b049ac9aafd6] not found in a registry.
```
Is this related to the open issue on registry?

**Comment by ChrisRackauckas** [comment]
It was just added last night. Maybe update the registry first?

**Comment by NirvikNU** [comment]
Yup its working now! Thanks!
